name: CI/CD Pipeline for Voting App
on:
  push:
    branches: [staging]

jobs:
  setup:
    name: Setup and Test
    runs-on: ubuntu-latest

    steps:
      - name: checkout-code
        uses: actions/checkout@v3

      - name: python-setup
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: install-python-denpendencies
        run: |
          cd vote/
          python -m pip install --upgrade pip
          pip install flake8

      - name: python-lint
        run: |
          cd vote/
          flake8 . --exclude=node_modules,migrations
